"""
Django settings for django_tutorial project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
import django_heroku
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m&+sz95f32-!1wuqgk2nz@x+uo6m&)#(731z*!4$ph%f$3mgp_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', 'mydjproj.herokuapp.com']
# ALLOWED_HOSTS = []



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'musics',
    'accounts',
    'rest_framework',
    'django_tutorial',
    'django_celery_beat',
    'django_celery_results',
    'musiclinebot'
]

#第二個LINE Bot(triplinebot)憑證
LINE_ACCESS_TOKEN = '7Es64smAgneY5DYiRAlOphe27Qy+DRuAQTQqmWNvulK2hHNt5eYLdYFrDdCy+GJvmy90+ZlKJGG/wKNbVvhzzLLJtRtBHvytgmVDmndc+vt+XfnXJ+zIm8IFnI93y8mO3KwpO/HafpoVpnzOi+ctFgdB04t89/1O/w1cDnyilFU='
LINE_SECRET = '64e6e502d960954f487d79645e98c7b7'

# REST_FRAMEWORK = {
#     'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.AcceptHeaderVersioning'
# }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.cache.UpdateCacheMiddleware',# 注意位置，在前
    'django.middleware.common.CommonMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',# 注意位置，在後
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CACHES ={
#     'default':{
#     'BACKEND':'django.core.cache.backends.db.DatabaseCache',
#     'LOCATION':'my_cache_table',# 要快取的表名
#     # 'TIMEOUT':5,# 預設的快取有效時間,以秒計. 預設值是 300 秒(五分鐘).
#     # 'OPTIONS':{
#     #     'MAX_ENTRIES':1000# 快取的最大條目數(超出該數舊的快取會被清除,預設值是 300).
#     #     }
#     }
# }

# CACHE_MIDDLEWARE_SECONDS =500

ROOT_URLCONF = 'django_tutorial.urls'


SETTING_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(SETTING_PATH, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_tutorial.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'techbebit',
        # 'HOST': 'localhost',
        'HOST': 'db',
        'PORT': '5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# SETTINGS_PATH = os.pa


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True

SITE_ID = 1

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# LOGIN_REDIRECT_URL = '/accounts/'
LOGIN_REDIRECT_URL = 'Home'

#------------------------CELERY--------------------------
# 最重要的設定，設定訊息broker,格式為：db://user:password@host:port/dbname
# 如果redis安裝在本機，使用localhost
# 如果docker部署的redis，使用redis://redis:6379
CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
# CELERY_BROKER_URL = "redis://redis:6379/0"

CELERY_ENABLE_UTC = True
# celery時區設定，建議與Django settings中TIME_ZONE同樣時區，防止時差
# Django設定時區需同時設定USE_TZ=True和TIME_ZONE = 'Asia/Shanghai'
CELERY_TIMEZONE = "Asia/Taipei"

# 為django_celery_results儲存Celery任務執行結果設定後臺
# 格式為：db+scheme://user:password@host:port/dbname
# 支援資料庫django-db和快取django-cache儲存任務狀態及結果
# CELERY_RESULT_BACKEND = "django-db"
# celery內容等訊息的格式設定，預設json
CELERY_ACCEPT_CONTENT = ['application/json', ]
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# 為任務設定超時時間，單位秒。超時即中止，執行下個任務。
CELERY_TASK_TIME_LIMIT = 5

# 為儲存結果設定過期日期，預設1天過期。如果beat開啟，Celery每天會自動清除。
# 設為0，儲存結果永不過期
CELERY_RESULT_EXPIRES = 0

# 任務限流
CELERY_TASK_ANNOTATIONS = {'tasks.add': {'rate_limit': '10/s'}}

# Worker並行數量，一般預設CPU核數，可以不設定
CELERY_WORKER_CONCURRENCY = 2

# 每個worker執行了多少任務就會死掉，預設是無限的
CELERY_WORKER_MAX_TASKS_PER_CHILD = 200

CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# 支持数据库django-db和缓存django-cache存储任务状态及结果
# 建议选django-db
CELERY_RESULT_BACKEND = "django-db"
#------------------------CELERY--------------------------

STATIC_URL = '/static'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
django_heroku.settings(locals())
