# Generated by Django 4.1.1 on 2022-09-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_music_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
