# Generated by Django 4.1.1 on 2022-09-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_music_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
