# Generated by Django 4.0.7 on 2022-10-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_alter_music_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='type',
        ),
        migrations.AddField(
            model_name='music',
            name='ranking',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='music',
            name='release_date',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='music',
            name='singer',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='music',
            name='song',
            field=models.TextField(default='Unknown'),
        ),
    ]
