# Generated by Django 3.2.16 on 2022-10-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0005_remove_music_type_music_ranking_music_release_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'get_latest_by': 'created'},
        ),
    ]
